export interface CultivationStage {
  stageNumber: number;
  stageName: string;
  stageNameOdia: string;
  timing: string;
  daysSpan: string;
  icon: string;
  keyGoal: string;
  tasks: string[];
  tasksOdia: string[];
  irrigationRule: string;
  nutritionAdvisory: string;
  weedManagement?: string;
  diseaseProtection: string;
  odiaSummary: string;
}

export interface WeeklyCalendarTask {
  week: number;
  title: string;
  titleOdia: string;
  activity: string;
  activityOdia: string;
  category: 'Land Prep' | 'Sowing' | 'Irrigation' | 'Nutrient' | 'Weeding' | 'Pest Scouting' | 'Harvest';
  criticality: 'High' | 'Medium' | 'Normal';
}

export interface CropFullGuide {
  id: string;
  name: string;
  nameOdia: string;
  variety: string;
  scientificName: string;
  category: 'Cereal' | 'Oilseed' | 'Pulse' | 'Millet';
  suitabilityScore: number;
  durationDays: string;
  expectedYield: string;
  avgPricePerQtl: string;
  netMarginPerAcre: string;
  waterSavingPct: number;
  overviewOdia: string;
  whySuitable: {
    title: string;
    description: string;
    points: { title: string; desc: string; icon: string }[];
    odiaExplanation: string;
  };
  howToGrowSummary: {
    soilType: string;
    seedRate: string;
    spacing: string;
    sowingWindow: string;
    fertilizerDose: string;
    irrigationFreq: string;
  };
  stages: CultivationStage[];
  calendar: WeeklyCalendarTask[];
}

export const CROPS_GUIDE_DATA: Record<string, CropFullGuide> = {
  paddy: {
    id: 'paddy',
    name: 'Paddy (Rice)',
    nameOdia: 'ଧାନ ଚାଷ (Swarna / MTU 1010)',
    variety: 'Swarna / MTU 1010 / Pooja',
    scientificName: 'Oryza sativa',
    category: 'Cereal',
    suitabilityScore: 88,
    durationDays: '125 - 135 days',
    expectedYield: '22 - 25 Quintals / acre',
    avgPricePerQtl: '₹2,300 (MSP)',
    netMarginPerAcre: '₹24,500',
    waterSavingPct: 0,
    overviewOdia: 'ଧାନ ଚାଷ ଓଡ଼ିଶାର ମୁଖ୍ୟ ଫସଲ। ସଠିକ ଜମି ପ୍ରସ୍ତୁତି, ସନ୍ତୁଳିତ ସାର ଓ ଜଳ ପରିଚାଳନା ଦ୍ୱାରା ଅଧିକ ଅମଳ ମିଳିପାରିବ।',
    whySuitable: {
      title: 'Suitability for High Rainfall & Clayey Alluvial Soils',
      description: 'Ideal for low-lying and canal-irrigated command areas with clay-loam water-retentive soils during Kharif season.',
      points: [
        { title: 'Established MSP Procurement', desc: '100% assured mandi procurement under Odisha State Civil Supplies Corporation.', icon: '🏛️' },
        { title: 'High Water Tolerance', desc: 'Can withstand seasonal waterlogging and torrential monsoon showers in Mayurbhanj.', icon: '🌧️' },
        { title: 'Fodder Security', desc: 'Provides high-volume straw for farm livestock and cattle feed throughout winter.', icon: '🌾' },
      ],
      odiaExplanation: 'ମୟୂରଭଞ୍ଜର ଖାଲୁଆ ଜମି ଏବଂ ମୌସୁମୀ ଜଳ ଉପଲବ୍ଧତା ଥିବା ଅଞ୍ଚଳ ପାଇଁ ଧାନ ଚାଷ ସବୁଠାରୁ ଅନୁକୂଳ। ସରକାରୀ ମଣ୍ଡିରେ ଧାର୍ଯ୍ୟ ଏମଏସପି ମୂଲ୍ୟରେ ବିକ୍ରି ସୁନିଶ୍ଚିତ।',
    },
    howToGrowSummary: {
      soilType: 'Clayey loam to heavy alluvial with pH 5.5 – 6.8',
      seedRate: '15 - 18 kg per acre (Transplanted)',
      spacing: '20 cm × 15 cm row-to-plant',
      sowingWindow: 'June 15 – July 15 (Nursery)',
      fertilizerDose: '35 kg N : 18 kg P2O5 : 18 kg K2O + 10 kg Zinc Sulphate',
      irrigationFreq: 'Maintain 2-5 cm water layer; alternate wetting & drying',
    },
    stages: [
      {
        stageNumber: 1,
        stageName: 'Land Preparation & Nursery Sowing',
        stageNameOdia: '୧. ଜମି ପ୍ରସ୍ତୁତି ଏବଂ ତଳି ଘାସ ବୁଣା',
        timing: 'When: Week 1',
        daysSpan: 'Days 1 – 25',
        icon: '🚜',
        keyGoal: 'Field leveling, puddling, and raising healthy disease-free seedlings.',
        tasks: [
          'Primary tillage with 2 passes of cultivator followed by rotavator',
          'Incorporate 4 tonnes well-decomposed FYM or compost per acre',
          'Puddle soil with standing water and level thoroughly using wooden plank',
          'Treat seeds with Carbendazim 2g / kg seed before sowing in nursery bed',
        ],
        tasksOdia: [
          'ଜମିକୁ ୨-୩ ଥର ଭଲଭାବେ ଚାଷ କରି ମାଟି ଗୁଣ୍ଡ କରନ୍ତୁ ଏବଂ ୪ ଟନ ଖତ ମିଶାନ୍ତୁ',
          'ପାଣି ଦେଇ କାଦୁଅ କରି ଭଲଭାବେ ସମତୁଲ କରନ୍ତୁ',
          'ବିହନ ଶୋଧନ ପାଇଁ କାର୍ବେଣ୍ଡାଜିମ ୨ ଗ୍ରାମ ପ୍ରତି କିଲୋ ବିହନରେ ମିଶାନ୍ତୁ',
          'ଉଚ୍ଚା ତଳି ଘାଟ ପ୍ରସ୍ତୁତ କରି ବିହନ ବୁଣନ୍ତୁ',
        ],
        irrigationRule: 'Maintain 2-3 cm shallow water in nursery beds during germination.',
        nutritionAdvisory: 'Basal application: 20 kg DAP + 15 kg MOP per acre during final puddling.',
        weedManagement: 'Apply Pretilachlor 50 EC @ 600 ml/acre within 3 days of sowing.',
        diseaseProtection: 'Seed treatment prevents primary blast and seedling rot.',
        odiaSummary: 'ପ୍ରଥମ ସପ୍ତାହରେ ଜମିକୁ ଭଲଭାବେ କାଦୁଅ କରି ଖତ ଦିଅନ୍ତୁ। ବିହନ ଶୋଧନ କରି ତଳି ପକାନ୍ତୁ।',
      },
      {
        stageNumber: 2,
        stageName: 'Sowing / Main Field Transplanting',
        stageNameOdia: '୨. ରୁଆ କାର୍ଯ୍ୟ (Transplanting)',
        timing: 'When: Week 2',
        daysSpan: 'Days 25 – 45',
        icon: '🌱',
        keyGoal: 'Proper spacing and seedling establishment in main field.',
        tasks: [
          'Transplant 20–25 day-old seedlings at 2–3 seedlings per hill',
          'Maintain 20 cm row-to-row and 15 cm plant-to-plant distance',
          'Complete gap filling within 7 days of transplanting to ensure uniform stand',
        ],
        tasksOdia: [
          '୨୦-୨୫ ଦିନର ତଳିକୁ ୨-୩ଟି ଲେଖାଏଁ ଗୁଚ୍ଛ କରି ରୁଅନ୍ତୁ',
          'ଧାଡ଼ିରୁ ଧାଡ଼ି ୨୦ ସେମି ଏବଂ ଗଛରୁ ଗଛ ୧୫ ସେମି ଦୂରତା ରଖନ୍ତୁ',
          '୭ ଦିନ ମଧ୍ୟରେ ଫାଙ୍କା ସ୍ଥାନରେ ତଳି ପୁନଃ ରୋପଣ କରନ୍ତୁ',
        ],
        irrigationRule: 'Maintain 2 cm water layer for first 10 days to encourage rapid root anchoring.',
        nutritionAdvisory: 'First top dressing: 15 kg Urea + 5 kg Zinc Sulphate at 15 DAT (Days After Transplanting).',
        weedManagement: 'Run cono-weeder at 15 DAT between rows to aerate root zone.',
        diseaseProtection: 'Scout for stem borer dead hearts; install pheromone traps @ 4/acre.',
        odiaSummary: '୨ୟ ସପ୍ତାହରେ ସଠିକ ଦୂରତାରେ ତଳି ରୁଅନ୍ତୁ ଏବଂ ୟୁରିଆ ସହିତ ଜିଙ୍କ ସାର ପ୍ରୟୋଗ କରନ୍ତୁ।',
      },
      {
        stageNumber: 3,
        stageName: 'Irrigation & Water Regime',
        stageNameOdia: '୩. ଜଳସେଚନ ପରିଚାଳନା',
        timing: 'When: According to crop stage and local conditions',
        daysSpan: 'Days 45 – 80',
        icon: '💧',
        keyGoal: 'Alternate Wetting and Drying (AWD) for deep root vigor and water economy.',
        tasks: [
          'Adopt Alternate Wetting & Drying (AWD): allow water to disappear for 2 days before re-flooding',
          'Keep 3-5 cm standing water strictly during panicle initiation and flowering',
          'Repair field bunds to prevent fertilizer leaching during heavy rain events',
        ],
        tasksOdia: [
          'ପାଣି ସବୁବେଳେ ଜମାଇ ନରଖି ୨ ଦିନ ଛାଡ଼ି ପାଣି ଦିଅନ୍ତୁ (AWD ପଦ୍ଧତି)',
          'ଫୁଲ ଆସିବା ସମୟରେ ୩-୫ ସେମି ପାଣି ସର୍ବଦା ବଜାୟ ରଖନ୍ତୁ',
          'ବନ୍ଧ ବାନ୍ଧି ପାଣି ଏବଂ ସାର ନଷ୍ଟ ହେବାରୁ ରକ୍ଷା କରନ୍ତୁ',
        ],
        irrigationRule: 'Critical moisture stages: Panicle initiation (50-60 DAT) and Grain filling (75-90 DAT).',
        nutritionAdvisory: 'Second top dressing: 15 kg Urea + 10 kg MOP at early panicle emergence.',
        weedManagement: 'Hand weed visible escapes or spray Bispyribac-sodium 10% SC @ 80 ml/acre.',
        diseaseProtection: 'Watch for bacterial leaf blight and sheath rot in humid weather.',
        odiaSummary: 'ଫସଲର ଗର୍ଭାଧାନ ଓ ଫୁଲ ଫୁଟିବା ସମୟରେ ପର୍ଯ୍ୟାପ୍ତ ଜଳସେଚନ କରନ୍ତୁ।',
      },
      {
        stageNumber: 4,
        stageName: 'Nutrient Management',
        stageNameOdia: '୪. ସନ୍ତୁଳିତ ସାର ଓ ପୋଷକ ତତ୍ତ୍ୱ',
        timing: 'When: Weeks 3, 6 & 9',
        daysSpan: 'Days 20 – 70',
        icon: '🧪',
        keyGoal: 'Split nitrogen and potassium doses to prevent lodging and maximize grain count.',
        tasks: [
          'Split total Nitrogen into 3 equal doses: 25% Basal, 50% Tillering, 25% Panicle',
          'Apply 100% Phosphorus at basal land preparation stage',
          'Apply Potassium in 2 splits (50% basal + 50% panicle initiation)',
        ],
        tasksOdia: [
          'ଯବକ୍ଷାରଜାନ (ୟୁରିଆ) ସାରକୁ ୩ ଭାଗ କରି ପ୍ରୟୋଗ କରନ୍ତୁ',
          'ସୁପର ବା DAP ସାର ଜମି ପ୍ରସ୍ତୁତି ସମୟରେ ଦିଅନ୍ତୁ',
          'ପୋଟାସ ସାରକୁ ଦୁଇଥର ଭାଗ କରି ଦିଅନ୍ତୁ ଯାହାଦ୍ୱାରା ଦାନା ପୁଷ୍ଟ ହେବ',
        ],
        irrigationRule: 'Irrigate immediately after top-dressing when soil is in moist condition.',
        nutritionAdvisory: 'Optional foliar spray: 1% 13-0-45 (Potassium Nitrate) for robust grain filling.',
        weedManagement: 'Clean bunds and remove wild grasses that consume fertilizer.',
        diseaseProtection: 'Avoid excessive nitrogen which invites Brown Plant Hopper (BPH).',
        odiaSummary: 'ସାରକୁ ୩ ଥରରେ ଭାଗ କରି ଦିଅନ୍ତୁ। ଅଧିକ ୟୁରିଆ ବ୍ୟବହାର କରନ୍ତୁ ନାହିଁ।',
      },
      {
        stageNumber: 5,
        stageName: 'Weed Management',
        stageNameOdia: '୫. ଘାସ ଦମନ ଓ ନିୟନ୍ତ୍ରଣ',
        timing: 'When: Weeks 3 – 5',
        daysSpan: 'Days 20 – 40',
        icon: '🌿',
        keyGoal: 'Eliminate weed competition before maximum tillering phase.',
        tasks: [
          'Use mechanical cono-weeder in line-transplanted fields at 15 and 30 DAT',
          'Hand pull sedges (Cyperus) and broadleaf weeds in non-mechanized plots',
          'Maintain standing water depth of 3 cm to naturally suppress weed seed germination',
        ],
        tasksOdia: [
          '୧୫ ଏବଂ ୩୦ ଦିନରେ କୋନୋ-ୱିଡ଼ର ଚଳାଇ ଘାସ ନଷ୍ଟ କରନ୍ତୁ',
          'ହାତରେ ମୋଥା ଏବଂ ଘାସ ଉପାଡ଼ି ଜମି ପରିଷ୍କାର ରଖନ୍ତୁ',
          '୩ ସେମି ପାଣି ରଖିଲେ ଅନାବନା ଘାସ ଗଜା ହୋଇପାରେ ନାହିଁ',
        ],
        irrigationRule: 'Do not drain water immediately after post-emergence herbicide spray.',
        nutritionAdvisory: 'Weed removal ensures 100% fertilizer uptake by rice tillers.',
        weedManagement: 'Spray Pyrazosulfuron Ethyl 10% WP @ 80g/acre at 3-7 DAT for mixed weed flora.',
        diseaseProtection: 'Weeds act as alternate hosts for viral vector leafhoppers.',
        odiaSummary: '୩ୟ ରୁ ୫ମ ସପ୍ତାହ ମଧ୍ୟରେ ଘାସ ବାଛି ଜମିକୁ ସମ୍ପୂର୍ଣ୍ଣ ସଫା ରଖନ୍ତୁ।',
      },
      {
        stageNumber: 6,
        stageName: 'Pest / Disease Monitoring',
        stageNameOdia: '୬. କୀଟ ଓ ରୋଗ ନିୟନ୍ତ୍ରଣ',
        timing: 'When: Weeks 5 – 10 (Continuous Scouting)',
        daysSpan: 'Days 40 – 90',
        icon: '🛡️',
        keyGoal: 'Early detection of stem borer, gall midge, leaf folder, blast, and BPH.',
        tasks: [
          'Weekly scouting: check 20 random hills for stem borer dead hearts & white ears',
          'Look at stem base for Brown Plant Hopper (BPH) hopper burn circles',
          'Spray Tricyclazole 75 WP @ 0.6g/L water at early spindle-shaped blast leaf spot appearance',
          'For BPH: Spray Pymetrozine 50% WDG @ 120g/acre directing spray nozzle to stem base',
        ],
        tasksOdia: [
          'ପ୍ରତି ସପ୍ତାହରେ କାଣ୍ଡବିନ୍ଧା ପୋକ ଓ ପତ୍ରମୋଡ଼ା ପୋକ ନିରୀକ୍ଷଣ କରନ୍ତୁ',
          'ଗଛ ମୂଳରେ ମାଟିଆ ଗୁଣ୍ଡି ପୋକ (BPH) ଯାଞ୍ଚ କରନ୍ତୁ',
          'ପତ୍ରପୋଡ଼ା ରୋଗ ପାଇଁ ଟ୍ରାଇସାଇକ୍ଲାଜୋଲ ଔଷଧ ସ୍ପ୍ରେ କରନ୍ତୁ',
          'ମାଟିଆ ଗୁଣ୍ଡି ପୋକ ଦେଖାଦେଲେ ପାଇମେଟ୍ରୋଜିନ୍ ସ୍ପ୍ରେ କରନ୍ତୁ',
        ],
        irrigationRule: 'Drain water for 24-36 hours if BPH population exceeds 10 hoppers per hill.',
        nutritionAdvisory: 'Avoid nitrogen sprays during active blast infection periods.',
        weedManagement: 'Clear border bunds to eliminate pest hibernation refuges.',
        diseaseProtection: 'Use light traps and yellow sticky traps for insect pest monitoring.',
        odiaSummary: 'ନିୟମିତ ପୋକ ଓ ରୋଗ ନିରୀକ୍ଷଣ କରନ୍ତୁ ଏବଂ ଆବଶ୍ୟକ ସ୍ଥଳେ ଉପଯୁକ୍ତ ଔଷଧ ସ୍ପ୍ରେ କରନ୍ତୁ।',
      },
      {
        stageNumber: 7,
        stageName: 'Harvest & Mandi Storage',
        stageNameOdia: '୭. ଅମଳ, ଶୁଖାଇବା ଏବଂ ମଣ୍ଡି ବିକ୍ରୟ',
        timing: 'When: Weeks 16 – 18',
        daysSpan: 'Days 120 – 135',
        icon: '🌾',
        keyGoal: 'Harvest at 85% golden maturity and dry grain to 14% moisture for Mandi procurement.',
        tasks: [
          'Drain field water completely 10–12 days prior to expected harvest date',
          'Harvest when 85-90% panicles turn golden straw color',
          'Thresh immediately and sun dry grains on tarpaulin sheets for 2–3 days',
          'Ensure grain moisture is below 14% to prevent Mandi deductions or fungal discoloration',
        ],
        tasksOdia: [
          'ଅମଳର ୧୦ ଦିନ ପୂର୍ବରୁ ଜମିରୁ ପାଣି ସମ୍ପୂର୍ଣ୍ଣ କାଢ଼ି ଦିଅନ୍ତୁ',
          '୮୫-୯୦% ଧାନ ପାଚି ସୁନେଲି ରଙ୍ଗ ହେଲେ କାଟି ଅମଳ କରନ୍ତୁ',
          'ତାରପାଲିନ ଉପରେ ୨-୩ ଦିନ ଶୁଖାଇ ଆର୍ଦ୍ରତା ୧୪% କୁ ଆଣନ୍ତୁ',
          'ସରକାରୀ ମଣ୍ଡିରେ ଟୋକନ ମାଧ୍ୟମରେ ବିକ୍ରି କରନ୍ତୁ',
        ],
        irrigationRule: 'Strictly zero irrigation during final 10 days before cutting.',
        nutritionAdvisory: 'Store in dry hermetic / polythene-lined jute bags with Neem leaves.',
        weedManagement: 'Remove wild rice rogues before threshing to keep seed pure.',
        diseaseProtection: 'Prevent grain discoloration by avoiding harvesting during rain showers.',
        odiaSummary: 'ଧାନ ସୁନେଲି ହେଲେ କାଟି ଭଲଭାବେ ଶୁଖାଇ ୧୪% ଆର୍ଦ୍ରତାରେ ମଣ୍ଡିରେ ବିକ୍ରି କରନ୍ତୁ।',
      },
    ],
    calendar: [
      { week: 1, title: 'Land Puddling & Nursery Sowing', titleOdia: 'ଜମି ପ୍ରସ୍ତୁତି ଓ ତଳି ପକାଇବା', activity: 'Tillage, manure 4 tonnes/acre, seed treatment with Carbendazim, nursery beds.', activityOdia: 'ଜମି ଚାଷ, ଖତ ପ୍ରୟୋଗ ଓ ବିହନ ଶୋଧନ।', category: 'Land Prep', criticality: 'High' },
      { week: 2, title: 'Nursery Care & Irrigation', titleOdia: 'ତଳି ଘାଟ ଯତ୍ନ', activity: 'Maintain 2cm water, spray urea 1% if seedlings appear pale.', activityOdia: 'ତଳିରେ ହାଲୁକା ପାଣି ରଖନ୍ତୁ।', category: 'Irrigation', criticality: 'Normal' },
      { week: 3, title: 'Main Field Final Puddling & Basal Fertilizer', titleOdia: 'ମୁଖ୍ୟ ଜମି କାଦୁଅ ଓ ମୂଳ ସାର', activity: 'Apply 20kg DAP + 15kg MOP during last pass of puddling.', activityOdia: 'ମୁଖ୍ୟ ଜମିରେ DAP ଓ MOP ସାର ଦିଅନ୍ତୁ।', category: 'Nutrient', criticality: 'High' },
      { week: 4, title: 'Transplanting & Line Spacing', titleOdia: 'ତଳି ରୁଆ କାର୍ଯ୍ୟ', activity: 'Transplant 2-3 seedlings/hill at 20cm x 15cm spacing. Apply Pretilachlor.', activityOdia: 'ଧାଡ଼ି କରି ତଳି ରୁଅନ୍ତୁ ଏବଂ ଘାସମରା ଔଷଧ ଦିଅନ୍ତୁ।', category: 'Sowing', criticality: 'High' },
      { week: 5, title: 'Gap Filling & 1st Weeding', titleOdia: 'ଫାଙ୍କା ସ୍ଥାନ ପୂରଣ ଓ କୋନୋ-ୱିଡ଼ର', activity: 'Gap fill within 7 days, run cono-weeder between rows.', activityOdia: 'ଫାଙ୍କା ସ୍ଥାନରେ ତଳି ଲଗାନ୍ତୁ ଓ ଘାସ ବାଛନ୍ତୁ।', category: 'Weeding', criticality: 'Medium' },
      { week: 6, title: '1st Nitrogen Top-Dressing & Zinc', titleOdia: 'ପ୍ରଥମ ୟୁରିଆ ଓ ଜିଙ୍କ ସାର', activity: '15kg Urea + 5kg Zinc Sulphate per acre in moist soil condition.', activityOdia: '୧୫ କିଗ୍ରା ୟୁରିଆ ଓ ୫ କିଗ୍ରା ଜିଙ୍କ ସଲଫେଟ ଦିଅନ୍ତୁ।', category: 'Nutrient', criticality: 'High' },
      { week: 7, title: 'AWD Water Regime & Stem Borer Scouting', titleOdia: 'ଜଳ ପରିଚାଳନା ଓ ପୋକ ନିରୀକ୍ଷଣ', activity: 'Alternate wetting & drying. Check for dead hearts. Install pheromone traps.', activityOdia: '୨ ଦିନ ଛାଡ଼ି ପାଣି ଦିଅନ୍ତୁ ଏବଂ ପୋକ ଯାଞ୍ଚ କରନ୍ତୁ।', category: 'Irrigation', criticality: 'Medium' },
      { week: 8, title: 'Active Tillering & 2nd Hand Weeding', titleOdia: 'ଶାଖା ବୃଦ୍ଧି ଓ ଘାସ ସଫା', activity: 'Ensure full crop canopy closure, remove border weeds.', activityOdia: 'ଜମିକୁ ସମ୍ପୂର୍ଣ୍ଣ ଘାସମୁକ୍ତ ରଖନ୍ତୁ।', category: 'Weeding', criticality: 'Normal' },
      { week: 9, title: 'Panicle Initiation & 2nd Top-Dressing', titleOdia: 'ଗର୍ଭାଧାନ ସମୟ ଓ ୨ୟ ସାର', activity: '15kg Urea + 10kg MOP. Maintain 4cm standing water strictly.', activityOdia: '୧୫ କିଗ୍ରା ୟୁରିଆ ଓ ୧୦ କିଗ୍ରା ପୋଟାସ ସାର ଦିଅନ୍ତୁ।', category: 'Nutrient', criticality: 'High' },
      { week: 10, title: 'Blast & Leaf Folder Preventive Spray', titleOdia: 'ପତ୍ରପୋଡ଼ା ରୋଗ ପ୍ରତିଷେଧକ ସ୍ପ୍ରେ', activity: 'Spray Tricyclazole 75 WP (0.6g/L) if cloudy/humid weather prevails.', activityOdia: 'ରୋଗ ପ୍ରତିରୋଧକ ଔଷଧ ସ୍ପ୍ରେ କରନ୍ତୁ।', category: 'Pest Scouting', criticality: 'High' },
      { week: 12, title: 'Flowering & BPH Stem Base Inspection', titleOdia: 'ଫୁଲ ଫୁଟିବା ଓ ଗୁଣ୍ଡି ପୋକ ଯାଞ୍ଚ', activity: 'Check stem base for BPH. Maintain continuous water saturation.', activityOdia: 'ଗଛ ମୂଳରେ ମାଟିଆ ଗୁଣ୍ଡି ପୋକ ଯାଞ୍ଚ କରନ୍ତୁ।', category: 'Pest Scouting', criticality: 'High' },
      { week: 14, title: 'Milky & Dough Stage Bird Scaring', titleOdia: 'ଦାନା ପୁଷ୍ଟ ସମୟ ଯତ୍ନ', activity: 'Optional 1% Potassium Nitrate foliar spray for grain weight.', activityOdia: '୧% ପୋଟାସିୟମ ନାଇଟ୍ରେଟ ସ୍ପ୍ରେ କରନ୍ତୁ।', category: 'Nutrient', criticality: 'Normal' },
      { week: 16, title: 'Field Drainage for Maturity', titleOdia: 'ଜମିରୁ ପାଣି ନିଷ୍କାସନ', activity: 'Stop irrigation completely 10-12 days before cut.', activityOdia: 'କାଟିବାର ୧୦ ଦିନ ପୂର୍ବରୁ ପାଣି ବନ୍ଦ କରନ୍ତୁ।', category: 'Irrigation', criticality: 'High' },
      { week: 17, title: 'Harvesting, Threshing & Sun Drying', titleOdia: 'ଅମଳ ଓ ଖରାରେ ଶୁଖାଇବା', activity: 'Harvest at 85% golden hue. Dry grain to 14% moisture.', activityOdia: 'ଧାନ କାଟି ଖରାରେ ୧୪% ଆର୍ଦ୍ରତା ପର୍ଯ୍ୟନ୍ତ ଶୁଖାନ୍ତୁ।', category: 'Harvest', criticality: 'High' },
    ],
  },

  groundnut: {
    id: 'groundnut',
    name: 'Groundnut (Peanut)',
    nameOdia: 'ଚିନାବାଦାମ ଚାଷ (TMV 2 / Kadiri 6)',
    variety: 'TMV 2 / Kadiri 6 / TAG 24 / Dharani',
    scientificName: 'Arachis hypogaea',
    category: 'Oilseed',
    suitabilityScore: 94,
    durationDays: '110 - 120 days',
    expectedYield: '12 - 15 Quintals / acre',
    avgPricePerQtl: '₹6,780 (MSP: ₹6,783)',
    netMarginPerAcre: '₹42,500',
    waterSavingPct: 58,
    overviewOdia: 'ଚିନାବାଦାମ ଧାନ ତୁଳନାରେ ୫୮% କମ୍ ପାଣି ଆବଶ୍ୟକ କରେ ଏବଂ ଏକର ପ୍ରତି ₹୪୨,୫୦୦ ପର୍ଯ୍ୟନ୍ତ ଶୁଦ୍ଧ ଲାଭ ଦିଏ।',
    whySuitable: {
      title: 'Why Groundnut is Highly Suitable for Your Farm',
      description: 'Groundnut is the #1 recommended climate-resilient crop for light sandy-loam & red soils with restricted canal water or borewell supply.',
      points: [
        { title: '58% Lower Water Consumption', desc: 'Requires only 4-5 light irrigations compared to continuous flooding in Paddy.', icon: '💧' },
        { title: 'Biological Nitrogen Fixation', desc: 'Root nodules fix 40-50 kg atmospheric nitrogen per acre, enriching soil fertility for next crop.', icon: '🌱' },
        { title: 'High Profit Margin (₹42,500/acre)', desc: 'Net margin is 73% higher than conventional paddy with robust oil-expeller buyer demand.', icon: '💰' },
        { title: 'High Quality Cattle Fodder', desc: 'Post-harvest groundnut haulms serve as protein-rich green/dry fodder for dairy cattle.', icon: '🐄' },
      ],
      odiaExplanation: 'ଚିନାବାଦାମ ଚାଷରେ ଧାନ ତୁଳନାରେ ଅଧା ପାଣି ଖର୍ଚ୍ଚ ହୁଏ, ଜମିର ଉର୍ବରତା ବୃଦ୍ଧି ପାଏ ଏବଂ ଏକର ପ୍ରତି ₹୪୨,୫୦୦ ପର୍ଯ୍ୟନ୍ତ ନିଟ୍ ଲାଭ ମିଳେ। ସ୍ଥାନୀୟ ବଜାରରେ ଏହାର ଚାହିଦା ବହୁତ ଅଧିକ।',
    },
    howToGrowSummary: {
      soilType: 'Well-drained sandy loam, red loamy soil with pH 6.0 – 7.5',
      seedRate: '45 - 50 kg kernels per acre (bunch type)',
      spacing: '30 cm row-to-row × 10 cm plant-to-plant',
      sowingWindow: 'Kharif: June–July | Rabi/Summer: Nov–Dec / Jan',
      fertilizerDose: '8 kg N : 16 kg P2O5 : 16 kg K2O + 100 kg Gypsum at pegging',
      irrigationFreq: '4 to 5 critical irrigations: Flowering, Pegging & Pod filling',
    },
    stages: [
      {
        stageNumber: 1,
        stageName: 'Land Preparation',
        stageNameOdia: '୧. ଜମି ପ୍ରସ୍ତୁତି (Land Preparation)',
        timing: 'When: Week 1',
        daysSpan: 'Days 1 – 10',
        icon: '🚜',
        keyGoal: 'Deep loose friable seedbed for easy peg penetration and pod development.',
        tasks: [
          'Plough 2–3 times to create a deep, loose, pulverised tilth (avoid hard clods)',
          'Apply 3–4 tonnes FYM / vermicompost per acre during secondary tillage',
          'Prepare broad bed and furrows (BBF) of 1.2m width for optimum drainage',
          'Form irrigation channels every 6–8 meters to avoid standing water puddles',
        ],
        tasksOdia: [
          'ଜମିକୁ ୨-୩ ଥର ଚାଷ କରି ମାଟିକୁ ଭଲଭାବେ ଗୁଣ୍ଡ କରନ୍ତୁ',
          'ଏକର ପ୍ରତି ୩-୪ ଟନ ଗୋବର ଖତ ବା କମ୍ପୋଷ୍ଟ ମାଟିରେ ମିଶାନ୍ତୁ',
          'ଜଳ ନିଷ୍କାସନ ପାଇଁ ୧.୨ ମିଟର ଚଉଡ଼ାର ବେଡ଼ (BBF) ପ୍ରସ୍ତୁତ କରନ୍ତୁ',
          'ଜମିରେ ପାଣି ଜମି ନରହିବା ପାଇଁ ନାଳି ବ୍ୟବସ୍ଥା କରନ୍ତୁ',
        ],
        irrigationRule: 'Give pre-sowing irrigation if soil lacks sufficient residual moisture.',
        nutritionAdvisory: 'Basal application: 20 kg DAP + 15 kg MOP + 10 kg Zinc Sulphate per acre.',
        weedManagement: 'Clean previous crop stubbles and weed roots completely.',
        diseaseProtection: 'Apply Trichoderma viride 1 kg mixed with 50 kg FYM to prevent collar rot.',
        odiaSummary: 'ପ୍ରଥମ ସପ୍ତାହରେ ଜମିକୁ ଗୁଣ୍ଡ କରି ଚାଷ କରନ୍ତୁ ଓ ଖତ ସହିତ ଟ୍ରାଇକୋଡର୍ମା ମିଶାନ୍ତୁ।',
      },
      {
        stageNumber: 2,
        stageName: 'Sowing & Seed Treatment',
        stageNameOdia: '୨. ବିହନ ବୁଣା ଓ ଶୋଧନ (Sowing)',
        timing: 'When: Week 2',
        daysSpan: 'Days 10 – 20',
        icon: '🌱',
        keyGoal: 'Uniform germination and optimum plant population (1.3 lakh plants/acre).',
        tasks: [
          'Select bold, undamaged kernels with intact seed coat (test germination >85%)',
          'Treat kernels with Mancozeb 2g + Carbendazim 1g per kg of seed',
          'Inoculate seeds with Rhizobium culture (200g/acre) and PSB culture for nitrogen fixation',
          'Sow at depth of 4–5 cm maintaining 30 cm × 10 cm spacing behind plough or seed drill',
        ],
        tasksOdia: [
          'ହୃଷ୍ଟପୃଷ୍ଟ ବିହନ ମଞ୍ଜି ବାଛନ୍ତୁ (ଗଜା କ୍ଷମତା >୮୫%)',
          'ମାଙ୍କୋଜେବ ୨ ଗ୍ରାମ ଓ କାର୍ବେଣ୍ଡାଜିମ ୧ ଗ୍ରାମ ପ୍ରତି କିଗ୍ରା ବିହନରେ ଶୋଧନ କରନ୍ତୁ',
          'ରାଇଜୋବିୟମ୍ ଓ ପିଏସବି କଲଚର ମଞ୍ଜିରେ ମିଶାଇ ଛାଇରେ ଶୁଖାନ୍ତୁ',
          'ଧାଡ଼ିରୁ ଧାଡ଼ି ୩୦ ସେମି ଏବଂ ଗଛରୁ ଗଛ ୧୦ ସେମି ଦୂରତାରେ ୪-୫ ସେମି ଗଭୀରରେ ବୁଣନ୍ତୁ',
        ],
        irrigationRule: 'Light post-sowing sprinkling if germination moisture is inadequate.',
        nutritionAdvisory: 'Avoid applying high urea at sowing; Rhizobium will synthesize nitrogen.',
        weedManagement: 'Spray Pendimethalin 30 EC @ 1.0 Litre/acre within 48 hours of sowing.',
        diseaseProtection: 'Seed treatment prevents Aspergillus crown rot and seedling blight.',
        odiaSummary: '୨ୟ ସପ୍ତାହରେ ରାଇଜୋବିୟମ ଶୋଧନ କରି ୩୦x୧୦ ସେମି ଦୂରତାରେ ବୁଣନ୍ତୁ।',
      },
      {
        stageNumber: 3,
        stageName: 'Irrigation & Critical Moisture Windows',
        stageNameOdia: '୩. ଜଳସେଚନ (Irrigation)',
        timing: 'When: According to crop stage and local conditions',
        daysSpan: 'Days 20 – 90',
        icon: '💧',
        keyGoal: 'Targeted irrigation at 3 critical physiological windows: Flowering, Pegging, Podding.',
        tasks: [
          'Window 1 (25-30 DAS): Light irrigation during early flowering',
          'Window 2 (40-45 DAS): Critical irrigation during peg entry into soil (crucial!)',
          'Window 3 (65-75 DAS): Pod filling & kernel development irrigation',
          'Never allow water stagnation: excessive water causes pod rotting and yellowing',
        ],
        tasksOdia: [
          '୧ମ ପାଳି (୨୫-୩୦ ଦିନ): ଫୁଲ ଫୁଟିବା ସମୟରେ ହାଲୁକା ପାଣି ଦିଅନ୍ତୁ',
          '୨ୟ ପାଳି (୪୦-୪୫ ଦିନ): ଛୁଇଁ ମାଟି ଭିତରକୁ ଯିବା ସମୟରେ ଅତି ଜରୁରୀ ପାଣି ଦିଅନ୍ତୁ',
          '୩ୟ ପାଳି (୬୫-୭୫ ଦିନ): ଫଳ ଭିତରେ ବାଦାମ ପୁଷ୍ଟ ହେବା ସମୟରେ ପାଣି ଦିଅନ୍ତୁ',
          'ଜମିରେ ପାଣି ଜମିବାକୁ ଦିଅନ୍ତୁ ନାହିଁ',
        ],
        irrigationRule: '4 to 5 light irrigations of 4-5 cm depth are sufficient for entire cycle.',
        nutritionAdvisory: 'Apply irrigation immediately after Gypsum broadcast at 45 DAS.',
        weedManagement: 'Avoid heavy flood irrigation which compacts surface soil and stops pegging.',
        diseaseProtection: 'Dry-wet alternate cycle prevents root-rot and collar-rot pathogens.',
        odiaSummary: 'ଫୁଲ ଫୁଟିବା, ଛୁଇଁ ମାଟି ଭିତରେ ପଶିବା ଓ ବାଦାମ ପୁଷ୍ଟ ହେବା ସମୟରେ ପାଣି ଦିଅନ୍ତୁ।',
      },
      {
        stageNumber: 4,
        stageName: 'Nutrient Management & Gypsum Application',
        stageNameOdia: '୪. ପୋଷକ ତତ୍ତ୍ୱ ଏବଂ ଜିପସମ ପ୍ରୟୋଗ',
        timing: 'When: Weeks 3 & 6 (Critical Gypsum at 45 DAS)',
        daysSpan: 'Days 20 – 50',
        icon: '🧪',
        keyGoal: 'Calcium and Sulphur supply via Gypsum for bold pod development and high oil content.',
        tasks: [
          'At 20 DAS: Foliar spray of 19-19-19 (10g/L) for rapid vegetative growth',
          'At 45 DAS (Pegging): Apply Gypsum @ 100 kg per acre around root zone and earth up',
          'Gypsum provides Calcium (prevents hollow pods/pops) and Sulphur (increases oil %)',
          'Foliar spray of 0.5% Ferrous Sulphate + 0.1% Citric acid if iron chlorosis appears',
        ],
        tasksOdia: [
          '୨୦ ଦିନରେ: 19:19:19 ସାର ସ୍ପ୍ରେ କରନ୍ତୁ',
          '୪୫ ଦିନରେ (ଛୁଇଁ ବାହାରିବା ସମୟରେ): ଏକର ପ୍ରତି ୧୦୦ କିଗ୍ରା ଜିପସମ୍ ପ୍ରୟୋଗ କରନ୍ତୁ',
          'ଜିପସମ୍ ଦ୍ୱାରା ବାଦାମ ଫମ୍ପା ହୁଏନାହିଁ ଏବଂ ତେଲ ପରିମାଣ ବଢ଼ିଥାଏ',
          'ପତ୍ର ହଳଦିଆ ପଡ଼ିଲେ ଫେରସ ସଲଫେଟ ସ୍ପ୍ରେ କରନ୍ତୁ',
        ],
        irrigationRule: 'Soil must be moist when applying Gypsum to facilitate root uptake.',
        nutritionAdvisory: 'Gypsum (100 kg/acre) at 45 DAS is the single most profitable input.',
        weedManagement: 'Combine gypsum application with light earthing-up and final weed removal.',
        diseaseProtection: 'Adequate calcium strengthens pod shell against soil-borne termites.',
        odiaSummary: '୪୫ ଦିନରେ ଏକର ପିଛା ୧୦୦ କିଗ୍ରା ଜିପସମ ଦେଇ ମୂଳରେ ମାଟି ଟେକି ଦିଅନ୍ତୁ।',
      },
      {
        stageNumber: 5,
        stageName: 'Weed Management & Earthing-Up',
        stageNameOdia: '୫. ଘାସ ଦମନ ଏବଂ ମାଟି ଟେକିବା (Earthing-up)',
        timing: 'When: Weeks 3 – 6 (Strictly before 45 DAS)',
        daysSpan: 'Days 20 – 45',
        icon: '🌿',
        keyGoal: 'Keep field 100% weed-free until pegging; never disturb soil after 45 DAS.',
        tasks: [
          'First intercultural operation / hoeing at 20–25 DAS to loosen topsoil',
          'Second hand weeding at 35–40 DAS along with light earthing-up',
          'CRITICAL RULE: DO NOT disturb soil or walk inside field after 45 DAS (breaks delicate pegs!)',
        ],
        tasksOdia: [
          '୨୦-୨୫ ଦିନରେ ପ୍ରଥମ ଥର ଖୁରୁପିରେ ଘାସ ବାଛି ମାଟି ହାଲୁକା କରନ୍ତୁ',
          '୩୫-୪୦ ଦିନରେ ଦ୍ୱିତୀୟ ଥର ଘାସ ବାଛି ଗଛ ମୂଳକୁ ମାଟି ଟେକନ୍ତୁ',
          'ସତର୍କତା: ୪୫ ଦିନ ପରେ ଜମି ଭିତରେ ଚାଲିବେ ନାହିଁ, ଛୁଇଁ ଭାଙ୍ଗିଯିବାର ଭୟ ଥାଏ',
        ],
        irrigationRule: 'Irrigate after completing earthing up to settle soil around pegs.',
        nutritionAdvisory: 'Earthing up puts loose soil directly in contact with developing pegs.',
        weedManagement: 'If pre-emergence herbicide was missed, spray Imazethapyr 10% SL @ 300 ml/acre at 15-20 DAS.',
        diseaseProtection: 'Weed removal improves aeration and reduces Tikka leaf spot severity.',
        odiaSummary: '୪୫ ଦିନ ପୂର୍ବରୁ ଘାସ ବାଛି ମାଟି ଟେକନ୍ତୁ। ତା’ପରେ ଜମି ଭିତରେ ଆଉ କୋଡ଼ନ୍ତୁ ନାହିଁ।',
      },
      {
        stageNumber: 6,
        stageName: 'Pest / Disease Monitoring (Tikka & Spodoptera)',
        stageNameOdia: '୬. ଟିକ୍କା ରୋଗ ଓ ପୋକ ନିୟନ୍ତ୍ରଣ',
        timing: 'When: Weeks 6 – 12',
        daysSpan: 'Days 40 – 85',
        icon: '🛡️',
        keyGoal: 'Protect foliage from Tikka leaf spot, rust, leaf miner, and collar rot.',
        tasks: [
          'Monitor for Tikka disease (circular dark spots with yellow halo on leaves)',
          'Spray Hexaconazole 5% EC @ 2ml/L or Tebuconazole 25.9% EC @ 1ml/L at first spot appearance',
          'For Spodoptera defoliators: install 4 pheromone traps/acre or spray Emamectin Benzoate @ 0.5g/L',
          'Inspect root crown for collar rot (Aspergillus niger) wilting symptoms',
        ],
        tasksOdia: [
          'ପତ୍ର ଉପରେ କଳା ଦାଗ (ଟିକ୍କା ରୋଗ) ଦେଖାଦେଲେ ତୁରନ୍ତ ଔଷଧ ସ୍ପ୍ରେ କରନ୍ତୁ',
          'ହେକ୍ସାକୋନାଜୋଲ (୨ ମିଲି ପ୍ରତି ଲିଟର) କିମ୍ବା ଟେବୁକୋନାଜୋଲ ସ୍ପ୍ରେ କରନ୍ତୁ',
          'ପତ୍ରଖିଆ ଶୁଣ୍ଢି ପୋକ ପାଇଁ ଏମାମେକ୍ଟିନ୍ ବେଞ୍ଜୋଏଟ୍ (୦.୫ ଗ୍ରାମ/ଲି) ସ୍ପ୍ରେ କରନ୍ତୁ',
          'ମୂଳ ସଢ଼ା ରୋଗ ପ୍ରତି ନଜର ରଖନ୍ତୁ',
        ],
        irrigationRule: 'Avoid sprinkler irrigation during active Tikka spore outbreak.',
        nutritionAdvisory: 'Foliar spray of 1% KNO3 (13-0-45) at 70 DAS boosts pod weight.',
        weedManagement: 'Keep field borders free of Parthenium and wild legume weeds.',
        diseaseProtection: 'Rotate fungicides between systemic (Tebuconazole) and contact (Mancozeb).',
        odiaSummary: 'ଟିକ୍କା ରୋଗ ଓ ପତ୍ରଖିଆ ପୋକ ପାଇଁ ହେକ୍ସାକୋନାଜୋଲ ଏବଂ ଏମାମେକ୍ଟିନ୍ ସ୍ପ୍ରେ କରନ୍ତୁ।',
      },
      {
        stageNumber: 7,
        stageName: 'Harvest, Stripping & Sun Drying',
        stageNameOdia: '୭. ଅମଳ, ଫଳ ତୋଳିବା ଏବଂ ଶୁଖାଇବା (Harvest)',
        timing: 'When: Weeks 16 – 17',
        daysSpan: 'Days 110 – 120',
        icon: '🥜',
        keyGoal: 'Harvest at peak kernel maturity when inner shell turns dark brownish-black.',
        tasks: [
          'Maturity test: Pull 2–3 plants; open shells. If inner shell lining is dark brownish, crop is ripe',
          'Give a light irrigation 2 days prior to harvest to ease plant pulling without snapping pods in soil',
          'Pull plants, strip pods using mechanical stripper or manual beating',
          'Sun dry pods on clean surface for 5–7 days until moisture drops below 8% (rattling sound)',
        ],
        tasksOdia: [
          'ପାକଳ ପରୀକ୍ଷା: ୨-୩ଟି ଗଛ ଉପାଡ଼ି ଚୋପା ଭିତର ପାଖ କଳା/ବାଦାମୀ ରଙ୍ଗ ହୋଇଛି କି ନାହିଁ ଦେଖନ୍ତୁ',
          'ଉପାଡ଼ିବାର ୨ ଦିନ ପୂର୍ବରୁ ହାଲୁକା ପାଣି ଦେଲେ ବାଦାମ ମାଟିରେ ଛିଣ୍ଡି ରହିବ ନାହିଁ',
          'ଗଛ ଉପାଡ଼ି ବାଦାମ ଛୁଇଁ ଅଲଗା କରନ୍ତୁ',
          'ଖରାରେ ୫-୭ ଦିନ ଶୁଖାଇ ଆର୍ଦ୍ରତା ୮% କୁ ଆଣନ୍ତୁ (ହାଲୁକା ଝଣଝଣ ଶବ୍ଦ ହେବ)',
        ],
        irrigationRule: 'Light pre-harvest irrigation makes soil soft and prevents 15-20% pod loss in dry soil.',
        nutritionAdvisory: 'Store dried pods in moisture-proof gunny bags elevated on wooden pallets.',
        weedManagement: 'Collect dry haulms; chop and store as rich cattle feed.',
        diseaseProtection: 'Keep moisture below 8% to strictly prevent deadly Aflatoxin mould formation.',
        odiaSummary: 'ପାଚିଗଲେ ହାଲୁକା ପାଣି ଦେଇ ଉପାଡ଼ନ୍ତୁ ଏବଂ ଖରାରେ ଶୁଖାଇ ୮% ଆର୍ଦ୍ରତାରେ ବିକ୍ରି କରନ୍ତୁ।',
      },
    ],
    calendar: [
      { week: 1, title: 'Field Tillage & Manure Incorporation', titleOdia: 'ଜମି ଚାଷ ଓ ଖତ ପ୍ରୟୋଗ', activity: '2-3 passes rotavator, apply 4 tonnes FYM + 1kg Trichoderma viride.', activityOdia: 'ଜମି ଚାଷ କରି ଖତ ଓ ଟ୍ରାଇକୋଡର୍ମା ମିଶାନ୍ତୁ।', category: 'Land Prep', criticality: 'High' },
      { week: 2, title: 'Seed Treatment & Sowing at 30x10 cm', titleOdia: 'ବିହନ ଶୋଧନ ଓ ବୁଣା', activity: 'Mancozeb + Rhizobium inoculation. Sow at 4-5cm depth. Apply Pendimethalin.', activityOdia: 'ରାଇଜୋବିୟମ ଶୋଧନ କରି ୩୦x୧୦ ସେମିରେ ବୁଣନ୍ତୁ।', category: 'Sowing', criticality: 'High' },
      { week: 3, title: 'Germination Inspection & Pre-Emergence Check', titleOdia: 'ଗଜା ଯାଞ୍ଚ ଓ ତନଖି', activity: 'Inspect seedling stand (ensure >90% emergence). Light hoeing.', activityOdia: 'ଗଜା ଯାଞ୍ଚ କରି ହାଲୁକା କୋଡ଼ନ୍ତୁ।', category: 'Land Prep', criticality: 'Normal' },
      { week: 4, title: '1st Hoeing & Weed Removal', titleOdia: 'ପ୍ରଥମ ଘାସ ବାଛିବା', activity: 'Manual weeding between rows. Spray 19-19-19 foliar fertilizer (10g/L).', activityOdia: 'ଘାସ ବାଛି 19:19:19 ସାର ସ୍ପ୍ରେ କରନ୍ତୁ।', category: 'Weeding', criticality: 'Medium' },
      { week: 5, title: '1st Irrigation at Early Flowering', titleOdia: 'ଫୁଲ ଆସିବା ସମୟରେ ୧ମ ପାଣି', activity: 'Provide light irrigation (3-4 cm) as golden-yellow flowers appear.', activityOdia: 'ଫୁଲ ଆସିବା ବେଳେ ହାଲୁକା ପାଣି ଦିଅନ୍ତୁ।', category: 'Irrigation', criticality: 'High' },
      { week: 6, title: 'Gypsum 100 kg/acre & Final Earthing-Up', titleOdia: 'ଜିପସମ ପ୍ରୟୋଗ ଓ ମାଟି ଟେକିବା', activity: 'Broadcast 100kg Gypsum around plants, earth up, do not disturb soil after this!', activityOdia: '୧୦୦ କିଗ୍ରା ଜିପସମ ଦେଇ ମୂଳରେ ମାଟି ଟେକନ୍ତୁ।', category: 'Nutrient', criticality: 'High' },
      { week: 7, title: 'Pegging Critical Irrigation (Peg Entry)', titleOdia: 'ଛୁଇଁ ମାଟିରେ ପଶିବା ସମୟରେ ପାଣି', activity: 'Keep soil moist so needles/pegs easily penetrate soil.', activityOdia: 'ମାଟି ନରମ ରଖିବା ପାଇଁ ପାଣି ଦିଅନ୍ତୁ।', category: 'Irrigation', criticality: 'High' },
      { week: 8, title: 'Tikka Disease Scouting & Preventive Spray', titleOdia: 'ଟିକ୍କା ରୋଗ ନିରୀକ୍ଷଣ', activity: 'Check lower leaves for dark brown spots. Spray Hexaconazole 5% EC (2ml/L).', activityOdia: 'ଟିକ୍କା ରୋଗ ପାଇଁ ହେକ୍ସାକୋନାଜୋଲ ସ୍ପ୍ରେ କରନ୍ତୁ।', category: 'Pest Scouting', criticality: 'High' },
      { week: 10, title: 'Pod Development & 3rd Irrigation', titleOdia: 'ବାଦାମ ପୁଷ୍ଟ ପାଇଁ ୩ୟ ପାଣି', activity: 'Ensure adequate moisture during kernel enlargement stage.', activityOdia: 'ଫଳ ପୁଷ୍ଟ ହେବା ପାଇଁ ପାଣି ଦିଅନ୍ତୁ।', category: 'Irrigation', criticality: 'Medium' },
      { week: 12, title: 'Spodoptera / Leaf Miner Monitoring', titleOdia: 'ପତ୍ରଖିଆ ପୋକ ନିୟନ୍ତ୍ରଣ', activity: 'Inspect for defoliator caterpillars. Spray Emamectin Benzoate if needed.', activityOdia: 'ଶୁଣ୍ଢି ପୋକ ପାଇଁ ଏମାମେକ୍ଟିନ୍ ସ୍ପ୍ରେ କରନ୍ତୁ।', category: 'Pest Scouting', criticality: 'Normal' },
      { week: 14, title: 'Foliar Booster for Bold Kernel Weight', titleOdia: 'ଫଳ ଓଜନ ବୃଦ୍ଧି ସ୍ପ୍ରେ', activity: 'Foliar spray of 1% Potassium Nitrate (13-0-45) for maximum shell filling.', activityOdia: 'ପୋଟାସିୟମ ନାଇଟ୍ରେଟ ସ୍ପ୍ରେ କରନ୍ତୁ।', category: 'Nutrient', criticality: 'Normal' },
      { week: 15, title: 'Pod Maturity Check & Pre-Harvest Soak', titleOdia: 'ପାକଳ ଯାଞ୍ଚ ଓ ହାଲୁକା ପାଣି', activity: 'Pull test plants; verify dark inner shell. Give light irrigation 2 days prior.', activityOdia: 'ପାକଳ ଯାଞ୍ଚ କରି ୨ ଦିନ ଆଗରୁ ହାଲୁକା ପାଣି ଦିଅନ୍ତୁ।', category: 'Harvest', criticality: 'High' },
      { week: 16, title: 'Harvesting, Stripping & Sun Drying', titleOdia: 'ଅମଳ, ଫଳ ତୋଳା ଓ ଶୁଖାଇବା', activity: 'Uproot plants, strip pods, sun dry to <8% moisture. Pack for Mandi sale.', activityOdia: 'ବାଦାମ ଉପାଡ଼ି ଖରାରେ ଶୁଖାଇ ମଣ୍ଡିରେ ବିକ୍ରି କରନ୍ତୁ।', category: 'Harvest', criticality: 'High' },
    ],
  },

  mustard: {
    id: 'mustard',
    name: 'Yellow Mustard / Rapeseed',
    nameOdia: 'ସୋରିଷ ଚାଷ (Pusa Bold / Anuradha)',
    variety: 'Pusa Bold / Anuradha (PT-303) / PM-25',
    scientificName: 'Brassica juncea',
    category: 'Oilseed',
    suitabilityScore: 92,
    durationDays: '100 - 110 days',
    expectedYield: '8 - 10 Quintals / acre',
    avgPricePerQtl: '₹5,950 (MSP: ₹5,950)',
    netMarginPerAcre: '₹36,800',
    waterSavingPct: 62,
    overviewOdia: 'ସୋରିଷ ଚାଷରେ ଧାନ ଅପେକ୍ଷା ୬୨% କମ୍ ପାଣି ଲାଗେ ଏବଂ ମାତ୍ର ୧୦୦ ଦିନରେ ଅମଳ ମିଳେ।',
    whySuitable: {
      title: 'Short Winter Turnaround with Guaranteed APMC Oil Demand',
      description: 'Perfect Rabi oilseed rotation crop utilizing post-kharif residual moisture with minimal capital expense.',
      points: [
        { title: '62% Water Conservation', desc: 'Requires only 2 to 3 light irrigations throughout its entire lifecycle.', icon: '💧' },
        { title: 'Short Duration (100 Days)', desc: 'Fast harvesting window allows early land clearance for summer vegetables/pulses.', icon: '⏱️' },
        { title: 'High Oil Content (38-42%)', desc: 'Local oil mills in Baripada & Betnoti offer premium spot cash over MSP.', icon: '🛢️' },
      ],
      odiaExplanation: 'ସୋରିଷ ମାତ୍ର ୧୦୦ ଦିନର ଫସଲ। ମାତ୍ର ୨-୩ଟି ପାଣିରେ ଉତ୍ତମ ଅମଳ ମିଳେ ଏବଂ ତେଲ କଳରେ ଉଚ୍ଚ ମୂଲ୍ୟରେ ବିକ୍ରି ହୁଏ।',
    },
    howToGrowSummary: {
      soilType: 'Light sandy loam to alluvial soils with good drainage',
      seedRate: '2.0 - 2.5 kg per acre',
      spacing: '30 cm row-to-row × 10 cm plant-to-plant',
      sowingWindow: 'October 15 – November 15 (Post-Kharif residual moisture)',
      fertilizerDose: '30 kg N : 15 kg P2O5 : 15 kg K2O + 10 kg Sulphur per acre',
      irrigationFreq: '2 critical irrigations: Rosette/Pre-flowering (30 DAS) & Pod fill (60 DAS)',
    },
    stages: [
      {
        stageNumber: 1,
        stageName: 'Land Preparation & Tilth',
        stageNameOdia: '୧. ଜମି ପ୍ରସ୍ତୁତି',
        timing: 'When: Week 1',
        daysSpan: 'Days 1 – 7',
        icon: '🚜',
        keyGoal: 'Fine pulverised moist seedbed to ensure small mustard seeds germinate quickly.',
        tasks: ['Plough 2 times with cultivator and plank immediately to conserve soil moisture', 'Incorporate 3 tonnes FYM + 10 kg elemental Sulphur / acre'],
        tasksOdia: ['ଜମିକୁ ୨ ଥର ଚାଷ କରି ମଇ ଦେଇ ମାଟି ଗୁଣ୍ଡ କରନ୍ତୁ', '୩ ଟନ ଖତ ଏବଂ ୧୦ କିଗ୍ରା ଗନ୍ଧକ (Sulphur) ମିଶାନ୍ତୁ'],
        irrigationRule: 'Conserve residual moisture from paddy harvest; do not let soil over-dry.',
        nutritionAdvisory: 'Apply full P, K and half dose of Nitrogen at final ploughing.',
        diseaseProtection: 'Seed treatment with Thiram @ 3g/kg seed.',
        odiaSummary: 'ଜମିକୁ ଭଲଭାବେ ଗୁଣ୍ଡ କରି ଖତ ଓ ସଲଫର ଦିଅନ୍ତୁ।',
      },
      {
        stageNumber: 2,
        stageName: 'Sowing & Thinning',
        stageNameOdia: '୨. ବିହନ ବୁଣା ଓ ବିରଳିକରଣ',
        timing: 'When: Week 2',
        daysSpan: 'Days 8 – 20',
        icon: '🌱',
        keyGoal: 'Optimum plant stand by timely thinning at 15 DAS.',
        tasks: ['Sow in lines 30 cm apart at 2-3 cm shallow depth', 'Mandatory thinning at 15 DAS to keep 10 cm between seedlings'],
        tasksOdia: ['୩୦ ସେମି ଦୂରତାରେ ୨-୩ ସେମି ଗଭୀରରେ ବୁଣନ୍ତୁ', '୧୫ ଦିନରେ ଅଧିକ ଗଛ ଉପାଡ଼ି ଗଛରୁ ଗଛ ୧୦ ସେମି ଦୂରତା ରଖନ୍ତୁ'],
        irrigationRule: 'Avoid waterlogging at germination stage.',
        nutritionAdvisory: 'Top dress remaining Nitrogen at 30 DAS before 1st irrigation.',
        diseaseProtection: 'Watch for mustard sawfly grubs on young cotyledon leaves.',
        odiaSummary: 'ଧାଡ଼ି କରି ବୁଣନ୍ତୁ ଏବଂ ୧୫ ଦିନରେ ଅଧିକ ଗଛ ବାଛି ୧୦ ସେମି ଦୂରତା ରଖନ୍ତୁ।',
      },
      {
        stageNumber: 3,
        stageName: 'Irrigation at Rosette & Podding',
        stageNameOdia: '୩. ଜଳସେଚନ ପରିଚାଳନା',
        timing: 'When: Weeks 4 & 8',
        daysSpan: 'Days 28 – 65',
        icon: '💧',
        keyGoal: '2 critical light irrigations at pre-flowering and siliqua formation.',
        tasks: ['1st Irrigation at 28-35 DAS (Pre-flowering / Rosette stage)', '2nd Irrigation at 60-65 DAS (Pod development stage)'],
        tasksOdia: ['୧ମ ପାଣି: ୨୮-୩୫ ଦିନରେ (ଫୁଲ ପୂର୍ବରୁ)', '୨ୟ ପାଣି: ୬୦-୬୫ ଦିନରେ (ଛୁଇଁ ବାନ୍ଧିବା ସମୟରେ)'],
        irrigationRule: 'Do not flood heavily during active flowering to avoid flower drop.',
        nutritionAdvisory: 'Sulphur enhances pungent oil aroma and seed weight.',
        diseaseProtection: 'Monitor for white rust and Alternaria blight in foggy weather.',
        odiaSummary: 'ମାତ୍ର ୨ଟି ପାଣି ଦିଅନ୍ତୁ: ଫୁଲ ପୂର୍ବରୁ ଓ ଛୁଇଁ ବାନ୍ଧିବା ବେଳେ।',
      },
      {
        stageNumber: 4,
        stageName: 'Nutrient Management',
        stageNameOdia: '୪. ସାର ପରିଚାଳନା',
        timing: 'When: Weeks 1 & 4',
        daysSpan: 'Days 1 – 35',
        icon: '🧪',
        keyGoal: 'Sulphur nutrition for maximum oil synthesis.',
        tasks: ['Apply 20 kg Urea + 10 kg Sulphur at 30 DAS', 'Foliar spray of 1% 00:52:34 at pod formation'],
        tasksOdia: ['୩୦ ଦିନରେ ୨୦ କିଗ୍ରା ୟୁରିଆ ଓ ୧୦ କିଗ୍ରା ସଲଫର ଦିଅନ୍ତୁ', 'ଫଳ ବାନ୍ଧିବା ବେଳେ 00:52:34 ସ୍ପ୍ରେ କରନ୍ତୁ'],
        irrigationRule: 'Apply top-dressing just before providing irrigation.',
        nutritionAdvisory: 'Sulphur deficiency leads to purple/yellow cupped leaves.',
        diseaseProtection: 'Adequate potassium prevents stem breaking under heavy pod load.',
        odiaSummary: 'ସୋରିଷରେ ଗନ୍ଧକ (Sulphur) ସାର ବ୍ୟବହାର କଲେ ତେଲ ଭଲ ହୁଏ।',
      },
      {
        stageNumber: 5,
        stageName: 'Weed Management',
        stageNameOdia: '୫. ଘାସ ଦମନ',
        timing: 'When: Weeks 3 – 4',
        daysSpan: 'Days 15 – 28',
        icon: '🌿',
        keyGoal: 'Keep field weed-free before crop canopy covers ground.',
        tasks: ['1 hand weeding at 20 DAS alongside thinning operation', 'Remove Orobanche (broomrape parasitic weed) if noticed'],
        tasksOdia: ['୨୦ ଦିନରେ ଥରେ ହାତରେ ଘାସ ବାଛି ପରିଷ୍କାର କରନ୍ତୁ', 'ପରଜୀବୀ ଘାସ (ଓରୋବାଙ୍କି) ଦେଖିଲେ ଉପାଡ଼ି ପୋଡ଼ି ଦିଅନ୍ତୁ'],
        irrigationRule: 'Weeding keeps soil loose for root expansion.',
        nutritionAdvisory: 'Clean field ensures complete fertilizer utilization.',
        diseaseProtection: 'Weeds harbor aphid colonies.',
        odiaSummary: '୨୦ ଦିନରେ ଥରେ ଘାସ ବାଛି ଜମି ସଫା ରଖନ୍ତୁ।',
      },
      {
        stageNumber: 6,
        stageName: 'Aphid Pest Management (ମହୁଆ ପୋକ)',
        stageNameOdia: '୬. ମହୁଆ ପୋକ ନିୟନ୍ତ୍ରଣ (Aphid)',
        timing: 'When: Weeks 7 – 10',
        daysSpan: 'Days 50 – 75',
        icon: '🛡️',
        keyGoal: 'Strict scouting for mustard aphid (Lipaphis erysimi) during cloudy winter.',
        tasks: ['Inspect central shoots & flowers for greenish aphid colonies', 'Spray Dimethoate 30 EC @ 1.7 ml/L or Thiamethoxam 25 WG @ 0.4 g/L during late afternoon'],
        tasksOdia: ['କଅଁଳ ଡାଳ ଓ ଫୁଲରେ ମହୁଆ ପୋକ ଯାଞ୍ଚ କରନ୍ତୁ', 'ମହୁଆ ପୋକ ପାଇଁ ଡାଇମେଥୋଏଟ୍ କିମ୍ବା ଥିଆମେଥୋକ୍ସାମ ଅପରାହ୍ନରେ ସ୍ପ୍ରେ କରନ୍ତୁ'],
        irrigationRule: 'Avoid excess watering in cloudy weather which increases aphid multiplication.',
        nutritionAdvisory: 'Spray after honeybees complete morning pollination (after 3 PM).',
        diseaseProtection: 'Use yellow sticky traps @ 6 per acre for early monitoring.',
        odiaSummary: 'ମହୁଆ ପୋକ ଲାଗିଲେ ଅପରାହ୍ନରେ ଥିଆମେଥୋକ୍ସାମ ଔଷଧ ସ୍ପ୍ରେ କରନ୍ତୁ।',
      },
      {
        stageNumber: 7,
        stageName: 'Harvest & Threshing',
        stageNameOdia: '୭. ଅମଳ ଓ ମଣ୍ଡି ବିକ୍ରୟ',
        timing: 'When: Weeks 14 – 15',
        daysSpan: 'Days 100 – 110',
        icon: '🌾',
        keyGoal: 'Harvest in morning hours when 75% pods turn yellowish to prevent shattering loss.',
        tasks: ['Cut crop in early morning when dew is present to avoid pod shattering', 'Bundle, dry on threshing floor for 4 days, thresh and store at <8% moisture'],
        tasksOdia: ['ସକାଳ ସମୟରେ କାଟନ୍ତୁ ଯାହାଦ୍ୱାରା ଛୁଇଁ ଫାଟି ଦାନା ଝଡ଼ିବ ନାହିଁ', '୪ ଦିନ ଖରାରେ ଶୁଖାଇ ବାଡ଼େଇ ଅମଳ କରନ୍ତୁ ଓ ୮% ଆର୍ଦ୍ରତାରେ ରଖନ୍ତୁ'],
        irrigationRule: 'No irrigation 20 days prior to harvest.',
        nutritionAdvisory: 'Mustard seed fetches direct high price in local tel-ghani markets.',
        diseaseProtection: 'Keep clean in dry gunny bags.',
        odiaSummary: 'ସକାଳେ କାଟି ଖରାରେ ଶୁଖାଇ ଅମଳ କରନ୍ତୁ।',
      },
    ],
    calendar: [
      { week: 1, title: 'Land Preparation & Sulphur', titleOdia: 'ଜମି ଚାଷ ଓ ଗନ୍ଧକ ସାର', activity: 'Tillage, apply FYM + 10kg Sulphur per acre.', activityOdia: 'ଜମି ଚାଷ କରି ଖତ ଓ ସଲଫର ଦିଅନ୍ତୁ।', category: 'Land Prep', criticality: 'High' },
      { week: 2, title: 'Sowing at 30cm Spacing', titleOdia: '୩୦ ସେମିରେ ବିହନ ବୁଣା', activity: 'Sow treated seeds at 2.5kg/acre in shallow furrows.', activityOdia: 'ଧାଡ଼ି କରି ବିହନ ବୁଣନ୍ତୁ।', category: 'Sowing', criticality: 'High' },
      { week: 3, title: 'Thinning & 1st Weeding', titleOdia: 'ଗଛ ବାଛିବା ଓ ଘାସ ସଫା', activity: 'Thin seedlings to 10cm apart, remove early weeds.', activityOdia: 'ଅଧିକ ଗଛ ବାଛି ୧୦ ସେମି ଦୂରତା ରଖନ୍ତୁ।', category: 'Weeding', criticality: 'High' },
      { week: 5, title: '1st Irrigation & Nitrogen Top-Dressing', titleOdia: '୧ମ ପାଣି ଓ ୟୁରିଆ ସାର', activity: 'Apply 20kg Urea, provide light irrigation at rosette stage.', activityOdia: 'ୟୁରିଆ ସାର ଦେଇ ହାଲୁକା ପାଣି ଦିଅନ୍ତୁ।', category: 'Irrigation', criticality: 'High' },
      { week: 8, title: 'Aphid Monitoring & 2nd Irrigation', titleOdia: 'ମହୁଆ ପୋକ ଯାଞ୍ଚ ଓ ୨ୟ ପାଣି', activity: 'Scout flowers for aphids, spray Thiamethoxam if >20 aphids/plant.', activityOdia: 'ମହୁଆ ପୋକ ଯାଞ୍ଚ କରି ଔଷଧ ସ୍ପ୍ରେ କରନ୍ତୁ।', category: 'Pest Scouting', criticality: 'High' },
      { week: 10, title: 'Pod Development & White Rust Check', titleOdia: 'ଛୁଇଁ ବାନ୍ଧିବା ଓ ରୋଗ ଯାଞ୍ଚ', activity: 'Inspect siliquae, foliar booster spray if required.', activityOdia: 'ଛୁଇଁ ପୁଷ୍ଟ ପାଇଁ ସ୍ପ୍ରେ କରନ୍ତୁ।', category: 'Nutrient', criticality: 'Normal' },
      { week: 14, title: 'Morning Harvest & Sun Drying', titleOdia: 'ସକାଳେ ଅମଳ ଓ ଶୁଖାଇବା', activity: 'Harvest when 75% pods turn yellow in morning dew.', activityOdia: 'ସକାଳେ କାଟି ଖରାରେ ଶୁଖାନ୍ତୁ।', category: 'Harvest', criticality: 'High' },
    ],
  },

  blackgram: {
    id: 'blackgram',
    name: 'Black Gram / Urad Dal',
    nameOdia: 'ବିରି ଚାଷ (PU 31 / Prasad)',
    variety: 'PU 31 / Prasad / Pant U 30 / Sarala',
    scientificName: 'Vigna mungo',
    category: 'Pulse',
    suitabilityScore: 90,
    durationDays: '75 - 85 days',
    expectedYield: '5 - 6 Quintals / acre',
    avgPricePerQtl: '₹7,400 (MSP: ₹7,400)',
    netMarginPerAcre: '₹31,200',
    waterSavingPct: 70,
    overviewOdia: 'ବିରି ଚାଷ ମାତ୍ର ୭୫-୮୦ ଦିନରେ ଅମଳ ଦିଏ, ୭୦% ପାଣି ସଞ୍ଚୟ କରେ ଓ ଜମିରେ ଯବକ୍ଷାରଜାନ ବୃଦ୍ଧି କରେ।',
    whySuitable: {
      title: 'Ultra-Fast 75-Day Pulse Crop with Assured MSP',
      description: 'Ideal catch crop after early rice harvest. Enriches soil nitrogen for subsequent seasons without heavy fertilizer input.',
      points: [
        { title: '70% Water Reduction', desc: 'Can grow on pure residual soil moisture with zero to 1 supplemental irrigation.', icon: '💧' },
        { title: 'Ultra-Short Duration (75 Days)', desc: 'Fastest cash turnaround of any kharif/rabi alternative in Odisha.', icon: '⚡' },
        { title: 'High MSP (₹7,400/Qtl)', desc: 'High market demand for dal processing with zero procurement price risk.', icon: '🏷️' },
      ],
      odiaExplanation: 'ବିରି ମାତ୍ର ୭୫ ଦିନର ଫସଲ। ଅଳ୍ପ ପାଣି ଓ କମ୍ ଖର୍ଚ୍ଚରେ ଏକର ପ୍ରତି ₹୩୧,୦୦୦ ରୁ ଅଧିକ ଲାଭ ମିଳିଥାଏ।',
    },
    howToGrowSummary: {
      soilType: 'Loamy to clay loam with good water retention and pH 6.5 – 7.5',
      seedRate: '8 - 10 kg per acre',
      spacing: '30 cm row-to-row × 10 cm plant-to-plant',
      sowingWindow: 'Kharif: June–July | Rabi (Paira): Oct–Nov',
      fertilizerDose: '8 kg N : 16 kg P2O5 : 8 kg K2O per acre (Basal DAP)',
      irrigationFreq: '1 critical irrigation at flowering/pod formation if winter rains fail',
    },
    stages: [
      {
        stageNumber: 1,
        stageName: 'Land Preparation',
        stageNameOdia: '୧. ଜମି ପ୍ରସ୍ତୁତି',
        timing: 'When: Week 1',
        daysSpan: 'Days 1 – 5',
        icon: '🚜',
        keyGoal: 'Adequate seedbed tilth without over-pulverizing.',
        tasks: ['1-2 ploughings followed by leveling plank', 'Incorporate 2 tonnes FYM per acre'],
        tasksOdia: ['୧-୨ ଥର ଚାଷ କରି ମଇ ଦିଅନ୍ତୁ', '୨ ଟନ ଖତ ମାଟିରେ ମିଶାନ୍ତୁ'],
        irrigationRule: 'Sow on moist soil or provide light pre-sowing irrigation.',
        nutritionAdvisory: 'Basal application: 20 kg DAP per acre.',
        diseaseProtection: 'Seed treatment with Trichoderma viride 4g/kg seed.',
        odiaSummary: 'ଜମିକୁ ହାଲୁକା ଚାଷ କରି DAP ସାର ପ୍ରୟୋଗ କରନ୍ତୁ।',
      },
      {
        stageNumber: 2,
        stageName: 'Seed Inoculation & Sowing',
        stageNameOdia: '୨. ବିହନ ଶୋଧନ ଓ ବୁଣା',
        timing: 'When: Week 2',
        daysSpan: 'Days 6 – 15',
        icon: '🌱',
        keyGoal: 'Rhizobium inoculation for effective root nodulation.',
        tasks: ['Treat with Rhizobium culture (200g/acre) and PSB', 'Sow at 30cm x 10cm spacing at 3-4 cm depth'],
        tasksOdia: ['ରାଇଜୋବିୟମ୍ କଲଚର ମିଶାଇ ବିହନ ଶୋଧନ କରନ୍ତୁ', '୩୦x୧୦ ସେମି ଦୂରତାରେ ବୁଣନ୍ତୁ'],
        irrigationRule: 'Maintain optimal moisture for quick 3-day germination.',
        nutritionAdvisory: 'Avoid applying excess nitrogen fertilizer.',
        diseaseProtection: 'Seed treatment protects from root rot and seed-borne blight.',
        odiaSummary: 'ରାଇଜୋବିୟମ ମିଶାଇ ଧାଡ଼ି କରି ବୁଣନ୍ତୁ।',
      },
      {
        stageNumber: 3,
        stageName: 'Irrigation & Flowering Moisture',
        stageNameOdia: '୩. ଜଳସେଚନ ପରିଚାଳନା',
        timing: 'When: Week 4 & 6',
        daysSpan: 'Days 25 – 45',
        icon: '💧',
        keyGoal: 'Provide moisture at flowering and pod filling.',
        tasks: ['1st light irrigation at 30-35 DAS (flowering initiation)', 'Avoid waterlogging which causes flower shedding'],
        tasksOdia: ['୩୦-୩୫ ଦିନରେ ଫୁଲ ଆସିବା ବେଳେ ହାଲୁକା ପାଣି ଦିଅନ୍ତୁ', 'ଜମିରେ ପାଣି ଜମିବାକୁ ଦିଅନ୍ତୁ ନାହିଁ'],
        irrigationRule: 'Only 1 to 2 light irrigations needed.',
        nutritionAdvisory: 'Spray 2% DAP foliar solution at flowering for high pod set.',
        diseaseProtection: 'Prevents drought-induced premature flower drop.',
        odiaSummary: 'ଫୁଲ ଆସିବା ସମୟରେ ଥରେ ହାଲୁକା ପାଣି ଦିଅନ୍ତୁ।',
      },
      {
        stageNumber: 4,
        stageName: 'Nutrient & Foliar Spray',
        stageNameOdia: '୪. ପୋଷକ ତତ୍ତ୍ୱ ଓ ସ୍ପ୍ରେ',
        timing: 'When: Week 4 & 6',
        daysSpan: 'Days 30 – 50',
        icon: '🧪',
        keyGoal: 'Foliar nutrition with 2% DAP or Pulse Wonder.',
        tasks: ['Spray 2% DAP foliar spray (20g/L) at flower initiation and 15 days later', 'Enhances pod count and seed boldness'],
        tasksOdia: ['ଫୁଲ ଆସିବା ବେଳେ ୨% DAP ସ୍ପ୍ରେ କରନ୍ତୁ', 'ଏହାଦ୍ୱାରା ଛୁଇଁ ସଂଖ୍ୟା ଓ ଦାନାର ଆକାର ବଢ଼ିଥାଏ'],
        irrigationRule: 'Spray in morning or late evening.',
        nutritionAdvisory: 'Foliar pulse nutrition gives 18-20% higher yield.',
        diseaseProtection: 'Balanced nutrition keeps plant resistant to viral vectors.',
        odiaSummary: '୨% DAP ସାର ସ୍ପ୍ରେ କଲେ ଅଧିକ ଛୁଇଁ ଲାଗେ।',
      },
      {
        stageNumber: 5,
        stageName: 'Weed Management',
        stageNameOdia: '୫. ଘାସ ଦମନ',
        timing: 'When: Week 3',
        daysSpan: 'Days 15 – 25',
        icon: '🌿',
        keyGoal: 'One critical hand weeding at 20 DAS.',
        tasks: ['1 hand weeding at 20 DAS', 'Or spray Imazethapyr @ 250ml/acre at 15-20 DAS for post-emergence weeds'],
        tasksOdia: ['୨୦ ଦିନରେ ଥରେ ଘାସ ବାଛନ୍ତୁ', 'ଘାସମରା ଔଷଧ ଇମାଜେଥାପିର ସ୍ପ୍ରେ କରିପାରିବେ'],
        irrigationRule: 'Weed removal ensures good light penetration.',
        nutritionAdvisory: 'Allows pulse branches to spread freely.',
        diseaseProtection: 'Reduces whitefly pest shelter.',
        odiaSummary: '୨୦ ଦିନରେ ଘାସ ବାଛି ଜମି ପରିଷ୍କାର ରଖନ୍ତୁ।',
      },
      {
        stageNumber: 6,
        stageName: 'Yellow Mosaic Virus & Pod Borer Scouting',
        stageNameOdia: '୬. ହଳଦିଆ ମୋଜାଇକ୍ ରୋଗ ଓ ଛୁଇଁବିନ୍ଧା ପୋକ',
        timing: 'When: Weeks 5 – 8',
        daysSpan: 'Days 35 – 60',
        icon: '🛡️',
        keyGoal: 'Control whitefly vector of Yellow Mosaic Virus (YMV) and spotted pod borer (Maruca).',
        tasks: ['For whitefly: Spray Acetamiprid 20% SP @ 0.5g/L or install yellow sticky traps', 'For pod borer: Spray Chlorantraniliprole 18.5% SC @ 0.3ml/L at early pod formation'],
        tasksOdia: ['ଧଳାମାଛି ଦମନ ପାଇଁ ଏସିଟାମିପ୍ରିଡ୍ ସ୍ପ୍ରେ କରନ୍ତୁ (ମୋଜାଇକ୍ ରୋଗ ରୋକିବା ପାଇଁ)', 'ଛୁଇଁବିନ୍ଧା ପୋକ ପାଇଁ କ୍ଲୋରାଣ୍ଟ୍ରାନିଲିପ୍ରୋଲ୍ ସ୍ପ୍ରେ କରନ୍ତୁ'],
        irrigationRule: 'Keep field borders clean.',
        nutritionAdvisory: 'Uproot and destroy YMV infected yellow mottled plants immediately.',
        diseaseProtection: 'Resistant varieties like PU 31 minimize viral risk.',
        odiaSummary: 'ଧଳାମାଛି ଓ ଛୁଇଁବିନ୍ଧା ପୋକ ପାଇଁ ଉପଯୁକ୍ତ ଔଷଧ ସ୍ପ୍ରେ କରନ୍ତୁ।',
      },
      {
        stageNumber: 7,
        stageName: 'Harvesting & Pod Drying',
        stageNameOdia: '୭. ଅମଳ ଓ ଶୁଖାଇବା',
        timing: 'When: Weeks 10 – 11',
        daysSpan: 'Days 75 – 85',
        icon: '🌾',
        keyGoal: 'Harvest when 80% pods turn blackish to prevent shattering.',
        tasks: ['Harvest pods by picking or cutting entire plants in morning hours', 'Sun dry on tarpaulin for 3 days, thresh and store at 9% moisture'],
        tasksOdia: ['୮୦% ଛୁଇଁ କଳା ପଡ଼ିଲେ ଗଛ କାଟି ଅମଳ କରନ୍ତୁ', '୩ ଦିନ ଖରାରେ ଶୁଖାଇ ବାଡ଼େଇ ୯% ଆର୍ଦ୍ରତାରେ ରଖନ୍ତୁ'],
        irrigationRule: 'No irrigation after pod maturity.',
        nutritionAdvisory: 'Roots left in soil decompose and add organic nitrogen.',
        diseaseProtection: 'Sun dry seeds before storage to avoid pulse beetle (bruchid) infestation.',
        odiaSummary: 'ଛୁଇଁ କଳା ହେଲେ କାଟି ଶୁଖାଇ ଅମଳ କରନ୍ତୁ।',
      },
    ],
    calendar: [
      { week: 1, title: 'Land Preparation & DAP', titleOdia: 'ଜମି ଚାଷ ଓ DAP ସାର', activity: 'Tillage, apply 20kg DAP + seed Rhizobium treatment.', activityOdia: 'ଚାଷ କରି DAP ସାର ଓ ରାଇଜୋବିୟମ ମିଶାନ୍ତୁ।', category: 'Land Prep', criticality: 'High' },
      { week: 2, title: 'Line Sowing at 30x10cm', titleOdia: 'ଧାଡ଼ି କରି ବୁଣା', activity: 'Sow at 8-10kg/acre in shallow moist soil.', activityOdia: 'ଧାଡ଼ି କରି ବିହନ ବୁଣନ୍ତୁ।', category: 'Sowing', criticality: 'High' },
      { week: 3, title: '1st Weeding & Stand Check', titleOdia: 'ଘାସ ବାଛିବା', activity: 'Hand weeding or Imazethapyr spray.', activityOdia: '୨୦ ଦିନରେ ଘାସ ବାଛନ୍ତୁ।', category: 'Weeding', criticality: 'Medium' },
      { week: 5, title: 'Flowering Irrigation & 2% DAP Spray', titleOdia: 'ଫୁଲ ସମୟ ପାଣି ଓ DAP ସ୍ପ୍ରେ', activity: 'Light irrigation + foliar spray of 2% DAP for flower retention.', activityOdia: 'ହାଲୁକା ପାଣି ଓ ୨% DAP ସ୍ପ୍ରେ କରନ୍ତୁ।', category: 'Irrigation', criticality: 'High' },
      { week: 7, title: 'Whitefly & Pod Borer Scouting', titleOdia: 'ଧଳାମାଛି ଓ ପୋକ ନିୟନ୍ତ୍ରଣ', activity: 'Spray Acetamiprid for whitefly; Chlorantraniliprole for pod borer.', activityOdia: 'ପୋକ ନିୟନ୍ତ୍ରଣ ଔଷଧ ସ୍ପ୍ରେ କରନ୍ତୁ।', category: 'Pest Scouting', criticality: 'High' },
      { week: 11, title: 'Harvesting & Threshing', titleOdia: 'ଅମଳ ଓ ଶୁଖାଇବା', activity: 'Cut plants when 80% pods turn black. Sun dry to 9% moisture.', activityOdia: 'ଛୁଇଁ କଳା ହେଲେ କାଟି ଶୁଖାନ୍ତୁ।', category: 'Harvest', criticality: 'High' },
    ],
  },
};
